language: bash
services: docker

env:
- VERSION=1.0

install:
  - git clone https://github.com/lvthillo/docker-backup-s3.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="lvthillo/backup-s3:$VERSION

script:
  - travis_retry docker build -t "$image"

after_script:
- docker images
