language: bash
services: docker

env:
- VERSION=1.0

install:
  - git clone https://github.com/lvthillo/docker-backup-s3.git

before_script:
  - env | sort
  - cd docker-backup-s3
  - image="lvthillo/backup-s3:$VERSION"

script:
  - travis_retry docker build -t "$image"

after_script:
- docker images
