language: bash
services: docker

env:
- VERSION=1.0 VARIANT=debian

install:
  - git clone https://github.com/lvthillo/docker-backup-s3.git ~/official-images

before_script:
  - env | sort
  - image="lvthillo/backup-s3:$VERSION" 

script:
  - travis_retry docker build -t "$image" "$VARIANT"
  - ~/official-images/test/run.sh "$image"

after_script:
- docker images
